### ISSUE TITLE
Probely testing causes Uncaught PHP Exception

### ISSUE THREAD

**Issue by ianmclaughlin** [Meteo-Concept/hcaptcha-bundle#16]
v4.10
	
`Uncaught PHP Exception TypeError: "MeteoConcept\HCaptchaBundle\Form\HCaptchaResponse::__construct(): Argument #1 ($response) must be of type string, array given, called in [my project path]/vendor/meteo-concept/hcaptcha-bundle/Form/DataTransformer/HCaptchaValueFetcher.php on line 88" at HCaptchaResponse.php line 37`

**Comment by lgeorget** [comment]
Hi,

Sorry about that problem. Do you mean v4.1.0?
I'm not sure what's happening in your case, do you have an array of h-captcha-response in the query string? You're not supposed to be able to submit multiple captchas at once.

**Comment by ianmclaughlin** [comment]
Hi, yes, v4.1.0 - sorry

Probely is a vulnerability scanner, and was able to craft and submit a response with an array instead of a string. Probely's job is to find things we're not supposed to be able to do.

I don't think it's a big problem because the user cannot continue, but graceful handling and subsequent failure would be preferred

**Comment by lgeorget** [comment]
On the one hand, it would certainly be nicer. On the other hand, I'm not against letting users face-plant when they deliberately try to craft invalid queries.
But who knows, there may be a valid way to actually end up with several captchas submitting in the same URL so I will handle it.

**Comment by lgeorget** [comment]
Fixed by c82cd3c807503ef5e826daf7d8ac34f894f653bd. The HCaptchaValueFetcher now throws a TransformationFailedException if it fails to construct a proper HCaptchaResponse value from the query. This is a much more correct way of doing things the Symfony way since it lets the app show a proper validation error in the form to the end user.

A unit test has been added for that case and a default, customisable, "invalid_message" option has been added to the HCaptcha form type to display a human-readable message to the end user.

Thank you for the report.
