### ISSUE TITLE
Symfony 3.2 issue

### ISSUE THREAD

**Issue by rustik666** [Meteo-Concept/hcaptcha-bundle#6]
Hi!

I got an error in my try to install the package to Symfony 3.2:

```
PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: [ERROR 1871] Element '{http://symfony.com/schema/dic/services}defaults': This element is not expected. Expected is ( {http://symfony.com/schema/dic/services}service ). (in /var/www/website/web/ - line 8, column 0) in /var/www/website/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:96
Stack trace:
#0 /var/www/website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(263): Symfony\Component\Config\Util\XmlUtils::loadFile('/var/www/websit...', Array)
#1 /var/www/website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/var/www/websit...')
#2 /var/www/website/vendor/meteo-concept/hcaptcha-bundle/DependencyInjection/MeteoConceptHCaptchaExtension.php(18): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('services.xml')
#3 /var/www/website/vendor/symf" while reading response header from upstream, client: 172.19.0.1, server: website, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "127.0.0.1:8080"

```

Could you please help me to figure it out? Thank you in advance!

**Comment by lgeorget** [comment]
Hi!

As explained in this page of the documentation: https://symfony.com/doc/3.4/service_container.html#creating-configuring-services-in-the-container, the "defaults" key in the services configuration file has appeared in Symfony 3.3. It's unavailable in Symfony 3.2 and this is why loading the file throws the error you see.

This package doesn't support Symfony 3.2. It does support Symfony 3.4 though and since there's no breaking change from 3.2 to 3.4 you should be able to upgrade your website without risk if you want to use the hcaptcha bundle.

You should anyway consider upgrading soon because even Symfony 3.4 is not maintained anymore so you'll run into a lot of these errors and you're also not protected against security vulnerabilities that won't get patched anymore in the future.
